#include "script_component.hpp"

#define ROW_SMALL_X			0.06
#define ROW_SMALL_Y 		0.63 //0.59
#define ROW_SMALL_W 		0.0118854
#define ROW_SMALL_H 		0.0118854
#define ROW_SMALL_OFFX 		0.005
#define ROW_SMALL_OFFY 		0.0104
#define ROW_SMALL_FONT_SIZE 0.015

#define VALUE(foo) foo

#define COMBINE(x,y) VALUE(x)VALUE(y)

#define BEGIN_CONTROL(name,idval) class name { idc = idval;
#define END_CONTROL		};

#define TEXT_ROW_ELEMENT(CONTROL_ID,WIDTH,HEIGHT,TEXT_X,TEXT_OFFSETX,OFFSET_NUMX,TEXT_Y,TEXT_OFFSETY,OFFSET_NUMY,FONT_SIZE)\
	BEGIN_CONTROL(CONTROL_ID, CONTROL_ID)\
		x = (((TEXT_X) * safeZoneW) + ((TEXT_OFFSETX*safeZoneW) * OFFSET_NUMX) + safeZoneX);\
		y = (((TEXT_Y) * safeZoneW) + ((TEXT_OFFSETY*safeZoneW) * OFFSET_NUMY) + safeZoneX);\
		w = WIDTH*SafeZoneW;\
		h = HEIGHT*SafeZoneW;\
		colorText[] = {0, 1, 0, 1};\
		sizeEx = FONT_SIZE*SafeZoneW;\
		type = CT_STATIC;\
		style = ST_LEFT;\
		font = "PixelSplitterBold";\
		colorBackground[] = {0, 0, 0, 0};\
		text = "";\
	END_CONTROL

#define TEXT_ROW_SMALL(ROW_ID, ROW_X, ROW_Y, ROW_NUMBER, ROW_W, ROW_H, ROW_OFFSETX, ROW_OFFSETY, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,001), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 0, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,002), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 1, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,003), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 2, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,004), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 3, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,005), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 4, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,006), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 5, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,007), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 6, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,008), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 7, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,009), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 8, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,010), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 9, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,011), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 10, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,012), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 11, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,013), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 12, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,014), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 13, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,015), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 14, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,016), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 15, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,017), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 16, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,018), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 17, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,019), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 18, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,020), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 19, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,021), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 20, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,022), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 21, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,023), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 22, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,024), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 23, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,025), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 24, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,026), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 25, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,027), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 26, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,028), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 27, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,029), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 28, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,030), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 29, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,031), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 30, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,032), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 31, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,033), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 32, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,034), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 33, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,035), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 34, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,036), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 35, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,037), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 36, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,038), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 37, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,039), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 38, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,040), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 39, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,041), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 40, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,042), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 41, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,043), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 42, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)\
	TEXT_ROW_ELEMENT(COMBINE(ROW_ID,044), ROW_W, ROW_H, ROW_X, ROW_OFFSETX, 43, ROW_Y, ROW_OFFSETY, ROW_NUMBER, FONT_SIZE)


class GVAR(OverlayDialog) {
	idd = 6421100;
	movingEnable = 0;
	
	name = QGVAR(OverlayDialog);
	duration = 999999;
	fadein = 0;
	onUnload = "";
	onLoad = "";
	
	ACE_textRowCount = 22;
	ACE_textColumnCount = 44;
	
	controlsBackground[] = {GVAR(BackgroundImage)};
	objects[] = {};
	class GVAR(BackgroundImage) {
		type = CT_STATIC;
		idc = 6421199;
		style = ST_PICTURE;
		colorBackground[] = {0, 0, 0, 0};
		colorText[] = {1, 1, 1, 1};
		font = EtelkaMonospaceProBold;
		sizeEx = 0.04;
		x = SafeZoneX;
		y = "(SafeZoneY + SafeZoneH) - (SafeZoneW * 0.35)";
		w = (SafeZoneW * 0.35);
		h = (SafeZoneW * 0.35);
		text = PATHTOF(data\TAD_background_ca.paa);
	};
	
	class controls {
		TEXT_ROW_SMALL(1, ROW_SMALL_X, ROW_SMALL_Y, 0, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(2, ROW_SMALL_X, ROW_SMALL_Y, 1, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(3, ROW_SMALL_X, ROW_SMALL_Y, 2, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(4, ROW_SMALL_X, ROW_SMALL_Y, 3, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(5, ROW_SMALL_X, ROW_SMALL_Y, 4, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(6, ROW_SMALL_X, ROW_SMALL_Y, 5, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(7, ROW_SMALL_X, ROW_SMALL_Y, 6, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(8, ROW_SMALL_X, ROW_SMALL_Y, 7, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(9, ROW_SMALL_X, ROW_SMALL_Y, 8, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(10, ROW_SMALL_X, ROW_SMALL_Y, 9, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(11, ROW_SMALL_X, ROW_SMALL_Y, 10, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(12, ROW_SMALL_X, ROW_SMALL_Y, 11, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(13, ROW_SMALL_X, ROW_SMALL_Y, 12, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(14, ROW_SMALL_X, ROW_SMALL_Y, 13, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(15, ROW_SMALL_X, ROW_SMALL_Y, 14, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(16, ROW_SMALL_X, ROW_SMALL_Y, 15, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(17, ROW_SMALL_X, ROW_SMALL_Y, 16, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(18, ROW_SMALL_X, ROW_SMALL_Y, 17, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(19, ROW_SMALL_X, ROW_SMALL_Y, 18, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(20, ROW_SMALL_X, ROW_SMALL_Y, 19, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(21, ROW_SMALL_X, ROW_SMALL_Y, 20, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
		TEXT_ROW_SMALL(22, ROW_SMALL_X, ROW_SMALL_Y, 21, ROW_SMALL_W, ROW_SMALL_H, ROW_SMALL_OFFX, ROW_SMALL_OFFY, ROW_SMALL_FONT_SIZE)
	};
};